apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: techshop
data:
  PRODUCT_SERVICE_URL: "http://product-service:8002"
  USER_SERVICE_URL: "http://user-service:8001"
  ORDER_SERVICE_URL: "http://order-service:8003"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
